//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.10.10 at 06:26:39 PM CST 
//


package com.xpsoft.netoa.entity;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the cn.shopin.syndata.oaupdata package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _UpdateInfo_QNAME = new QName("http://syndata.shopin.cn/OAUpdata", "UpdateInfo");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: cn.shopin.syndata.oaupdata
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link UpdateInfo }
     * 
     */
    public UpdateInfo createUpdateInfo() {
        return new UpdateInfo();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UpdateInfo }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://syndata.shopin.cn/OAUpdata", name = "UpdateInfo")
    public JAXBElement<UpdateInfo> createUpdateInfo(UpdateInfo value) {
        return new JAXBElement<UpdateInfo>(_UpdateInfo_QNAME, UpdateInfo.class, null, value);
    }

}
