//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.12.01 at 03:21:14 ÏÂÎç CST 
//


package net.shopin.alipay.entity;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all minOccurs="0">
 *         &lt;element name="is_success" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="request" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="param" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;simpleContent>
 *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                           &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/extension>
 *                       &lt;/simpleContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="response" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;all>
 *                   &lt;element name="trade" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;all>
 *                             &lt;element name="body" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="buyer_email" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="buyer_id" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="coupon_used_fee" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="discount" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="flag_trade_locked" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="gmt_create" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="gmt_last_modified_time" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="gmt_payment" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="is_total_fee_adjust" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="out_trade_no" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="payment_type" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="price" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="quantity" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="seller_email" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="seller_id" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="subject" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="to_buyer_fee" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="to_seller_fee" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="total_fee" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="trade_no" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="trade_status" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="use_coupon" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="logistics_fee" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="coupon_discount" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="refund_status" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="logistics_status" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="additional_trade_status" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="gmt_send_goods" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="gmt_refund" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="time_out" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="gmt_close" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="gmt_logistics_modify" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="time_out_type" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="refund_fee" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="refund_flow_type" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="refund_id" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="refund_cash_fee" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="refund_coupon_fee" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="refund_agent_pay_fee" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="fund_bill_list" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                           &lt;/all>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/all>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="sign" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="sign_type" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="error" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {

})
@XmlRootElement(name = "alipay")
public class Alipay {

    @XmlElement(name = "is_success")
    protected String isSuccess;
    protected Alipay.Request request;
    protected Alipay.Response response;
    protected String sign;
    @XmlElement(name = "sign_type")
    protected String signType;
    protected String error;

    /**
     * Gets the value of the isSuccess property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIsSuccess() {
        return isSuccess;
    }

    /**
     * Sets the value of the isSuccess property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIsSuccess(String value) {
        this.isSuccess = value;
    }

    /**
     * Gets the value of the request property.
     * 
     * @return
     *     possible object is
     *     {@link Alipay.Request }
     *     
     */
    public Alipay.Request getRequest() {
        return request;
    }

    /**
     * Sets the value of the request property.
     * 
     * @param value
     *     allowed object is
     *     {@link Alipay.Request }
     *     
     */
    public void setRequest(Alipay.Request value) {
        this.request = value;
    }

    /**
     * Gets the value of the response property.
     * 
     * @return
     *     possible object is
     *     {@link Alipay.Response }
     *     
     */
    public Alipay.Response getResponse() {
        return response;
    }

    /**
     * Sets the value of the response property.
     * 
     * @param value
     *     allowed object is
     *     {@link Alipay.Response }
     *     
     */
    public void setResponse(Alipay.Response value) {
        this.response = value;
    }

    /**
     * Gets the value of the sign property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSign() {
        return sign;
    }

    /**
     * Sets the value of the sign property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSign(String value) {
        this.sign = value;
    }

    /**
     * Gets the value of the signType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSignType() {
        return signType;
    }

    /**
     * Sets the value of the signType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSignType(String value) {
        this.signType = value;
    }

    /**
     * Gets the value of the error property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getError() {
        return error;
    }

    /**
     * Sets the value of the error property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setError(String value) {
        this.error = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="param" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;simpleContent>
     *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *                 &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/extension>
     *             &lt;/simpleContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "param"
    })
    public static class Request {

        @XmlElement(nillable = true)
        protected List<Alipay.Request.Param> param;

        /**
         * Gets the value of the param property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the param property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getParam().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Alipay.Request.Param }
         * 
         * 
         */
        public List<Alipay.Request.Param> getParam() {
            if (param == null) {
                param = new ArrayList<Alipay.Request.Param>();
            }
            return this.param;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;simpleContent>
         *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
         *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/extension>
         *   &lt;/simpleContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "value"
        })
        public static class Param {

            @XmlValue
            protected String value;
            @XmlAttribute
            protected String name;

            /**
             * Gets the value of the value property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getValue() {
                return value;
            }

            /**
             * Sets the value of the value property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setValue(String value) {
                this.value = value;
            }

            /**
             * Gets the value of the name property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getName() {
                return name;
            }

            /**
             * Sets the value of the name property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setName(String value) {
                this.name = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;all>
     *         &lt;element name="trade" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;all>
     *                   &lt;element name="body" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="buyer_email" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="buyer_id" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="coupon_used_fee" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="discount" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="flag_trade_locked" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="gmt_create" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="gmt_last_modified_time" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="gmt_payment" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="is_total_fee_adjust" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="out_trade_no" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="payment_type" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="price" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="quantity" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="seller_email" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="seller_id" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="subject" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="to_buyer_fee" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="to_seller_fee" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="total_fee" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="trade_no" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="trade_status" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="use_coupon" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="logistics_fee" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="coupon_discount" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="refund_status" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="logistics_status" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="additional_trade_status" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="gmt_send_goods" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="gmt_refund" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="time_out" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="gmt_close" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="gmt_logistics_modify" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="time_out_type" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="refund_fee" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="refund_flow_type" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="refund_id" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="refund_cash_fee" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="refund_coupon_fee" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="refund_agent_pay_fee" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="fund_bill_list" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                 &lt;/all>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/all>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {

    })
    public static class Response {

        protected Alipay.Response.Trade trade;

        /**
         * Gets the value of the trade property.
         * 
         * @return
         *     possible object is
         *     {@link Alipay.Response.Trade }
         *     
         */
        public Alipay.Response.Trade getTrade() {
            return trade;
        }

        /**
         * Sets the value of the trade property.
         * 
         * @param value
         *     allowed object is
         *     {@link Alipay.Response.Trade }
         *     
         */
        public void setTrade(Alipay.Response.Trade value) {
            this.trade = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;all>
         *         &lt;element name="body" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="buyer_email" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="buyer_id" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="coupon_used_fee" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="discount" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="flag_trade_locked" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="gmt_create" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="gmt_last_modified_time" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="gmt_payment" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="is_total_fee_adjust" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="out_trade_no" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="payment_type" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="price" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="quantity" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="seller_email" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="seller_id" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="subject" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="to_buyer_fee" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="to_seller_fee" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="total_fee" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="trade_no" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="trade_status" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="use_coupon" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="logistics_fee" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="coupon_discount" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="refund_status" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="logistics_status" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="additional_trade_status" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="gmt_send_goods" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="gmt_refund" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="time_out" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="gmt_close" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="gmt_logistics_modify" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="time_out_type" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="refund_fee" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="refund_flow_type" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="refund_id" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="refund_cash_fee" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="refund_coupon_fee" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="refund_agent_pay_fee" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="fund_bill_list" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *       &lt;/all>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {

        })
        public static class Trade {

            protected String body;
            @XmlElement(name = "buyer_email")
            protected String buyerEmail;
            @XmlElement(name = "buyer_id")
            protected String buyerId;
            @XmlElement(name = "coupon_used_fee")
            protected String couponUsedFee;
            protected String discount;
            @XmlElement(name = "flag_trade_locked")
            protected String flagTradeLocked;
            @XmlElement(name = "gmt_create")
            protected String gmtCreate;
            @XmlElement(name = "gmt_last_modified_time")
            protected String gmtLastModifiedTime;
            @XmlElement(name = "gmt_payment")
            protected String gmtPayment;
            @XmlElement(name = "is_total_fee_adjust")
            protected String isTotalFeeAdjust;
            @XmlElement(name = "out_trade_no")
            protected String outTradeNo;
            @XmlElement(name = "payment_type")
            protected String paymentType;
            protected String price;
            protected String quantity;
            @XmlElement(name = "seller_email")
            protected String sellerEmail;
            @XmlElement(name = "seller_id")
            protected String sellerId;
            protected String subject;
            @XmlElement(name = "to_buyer_fee")
            protected String toBuyerFee;
            @XmlElement(name = "to_seller_fee")
            protected String toSellerFee;
            @XmlElement(name = "total_fee")
            protected String totalFee;
            @XmlElement(name = "trade_no")
            protected String tradeNo;
            @XmlElement(name = "trade_status")
            protected String tradeStatus;
            @XmlElement(name = "use_coupon")
            protected String useCoupon;
            @XmlElement(name = "logistics_fee")
            protected String logisticsFee;
            @XmlElement(name = "coupon_discount")
            protected String couponDiscount;
            @XmlElement(name = "refund_status")
            protected String refundStatus;
            @XmlElement(name = "logistics_status")
            protected String logisticsStatus;
            @XmlElement(name = "additional_trade_status")
            protected String additionalTradeStatus;
            @XmlElement(name = "gmt_send_goods")
            protected String gmtSendGoods;
            @XmlElement(name = "gmt_refund")
            protected String gmtRefund;
            @XmlElement(name = "time_out")
            protected String timeOut;
            @XmlElement(name = "gmt_close")
            protected String gmtClose;
            @XmlElement(name = "gmt_logistics_modify")
            protected String gmtLogisticsModify;
            @XmlElement(name = "time_out_type")
            protected String timeOutType;
            @XmlElement(name = "refund_fee")
            protected String refundFee;
            @XmlElement(name = "refund_flow_type")
            protected String refundFlowType;
            @XmlElement(name = "refund_id")
            protected String refundId;
            @XmlElement(name = "refund_cash_fee")
            protected String refundCashFee;
            @XmlElement(name = "refund_coupon_fee")
            protected String refundCouponFee;
            @XmlElement(name = "refund_agent_pay_fee")
            protected String refundAgentPayFee;
            @XmlElement(name = "fund_bill_list")
            protected String fundBillList;

            /**
             * Gets the value of the body property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getBody() {
                return body;
            }

            /**
             * Sets the value of the body property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setBody(String value) {
                this.body = value;
            }

            /**
             * Gets the value of the buyerEmail property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getBuyerEmail() {
                return buyerEmail;
            }

            /**
             * Sets the value of the buyerEmail property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setBuyerEmail(String value) {
                this.buyerEmail = value;
            }

            /**
             * Gets the value of the buyerId property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getBuyerId() {
                return buyerId;
            }

            /**
             * Sets the value of the buyerId property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setBuyerId(String value) {
                this.buyerId = value;
            }

            /**
             * Gets the value of the couponUsedFee property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCouponUsedFee() {
                return couponUsedFee;
            }

            /**
             * Sets the value of the couponUsedFee property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCouponUsedFee(String value) {
                this.couponUsedFee = value;
            }

            /**
             * Gets the value of the discount property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getDiscount() {
                return discount;
            }

            /**
             * Sets the value of the discount property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setDiscount(String value) {
                this.discount = value;
            }

            /**
             * Gets the value of the flagTradeLocked property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getFlagTradeLocked() {
                return flagTradeLocked;
            }

            /**
             * Sets the value of the flagTradeLocked property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setFlagTradeLocked(String value) {
                this.flagTradeLocked = value;
            }

            /**
             * Gets the value of the gmtCreate property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getGmtCreate() {
                return gmtCreate;
            }

            /**
             * Sets the value of the gmtCreate property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setGmtCreate(String value) {
                this.gmtCreate = value;
            }

            /**
             * Gets the value of the gmtLastModifiedTime property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getGmtLastModifiedTime() {
                return gmtLastModifiedTime;
            }

            /**
             * Sets the value of the gmtLastModifiedTime property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setGmtLastModifiedTime(String value) {
                this.gmtLastModifiedTime = value;
            }

            /**
             * Gets the value of the gmtPayment property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getGmtPayment() {
                return gmtPayment;
            }

            /**
             * Sets the value of the gmtPayment property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setGmtPayment(String value) {
                this.gmtPayment = value;
            }

            /**
             * Gets the value of the isTotalFeeAdjust property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getIsTotalFeeAdjust() {
                return isTotalFeeAdjust;
            }

            /**
             * Sets the value of the isTotalFeeAdjust property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setIsTotalFeeAdjust(String value) {
                this.isTotalFeeAdjust = value;
            }

            /**
             * Gets the value of the outTradeNo property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getOutTradeNo() {
                return outTradeNo;
            }

            /**
             * Sets the value of the outTradeNo property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setOutTradeNo(String value) {
                this.outTradeNo = value;
            }

            /**
             * Gets the value of the paymentType property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getPaymentType() {
                return paymentType;
            }

            /**
             * Sets the value of the paymentType property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setPaymentType(String value) {
                this.paymentType = value;
            }

            /**
             * Gets the value of the price property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getPrice() {
                return price;
            }

            /**
             * Sets the value of the price property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setPrice(String value) {
                this.price = value;
            }

            /**
             * Gets the value of the quantity property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getQuantity() {
                return quantity;
            }

            /**
             * Sets the value of the quantity property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setQuantity(String value) {
                this.quantity = value;
            }

            /**
             * Gets the value of the sellerEmail property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getSellerEmail() {
                return sellerEmail;
            }

            /**
             * Sets the value of the sellerEmail property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setSellerEmail(String value) {
                this.sellerEmail = value;
            }

            /**
             * Gets the value of the sellerId property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getSellerId() {
                return sellerId;
            }

            /**
             * Sets the value of the sellerId property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setSellerId(String value) {
                this.sellerId = value;
            }

            /**
             * Gets the value of the subject property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getSubject() {
                return subject;
            }

            /**
             * Sets the value of the subject property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setSubject(String value) {
                this.subject = value;
            }

            /**
             * Gets the value of the toBuyerFee property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getToBuyerFee() {
                return toBuyerFee;
            }

            /**
             * Sets the value of the toBuyerFee property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setToBuyerFee(String value) {
                this.toBuyerFee = value;
            }

            /**
             * Gets the value of the toSellerFee property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getToSellerFee() {
                return toSellerFee;
            }

            /**
             * Sets the value of the toSellerFee property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setToSellerFee(String value) {
                this.toSellerFee = value;
            }

            /**
             * Gets the value of the totalFee property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getTotalFee() {
                return totalFee;
            }

            /**
             * Sets the value of the totalFee property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setTotalFee(String value) {
                this.totalFee = value;
            }

            /**
             * Gets the value of the tradeNo property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getTradeNo() {
                return tradeNo;
            }

            /**
             * Sets the value of the tradeNo property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setTradeNo(String value) {
                this.tradeNo = value;
            }

            /**
             * Gets the value of the tradeStatus property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getTradeStatus() {
                return tradeStatus;
            }

            /**
             * Sets the value of the tradeStatus property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setTradeStatus(String value) {
                this.tradeStatus = value;
            }

            /**
             * Gets the value of the useCoupon property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getUseCoupon() {
                return useCoupon;
            }

            /**
             * Sets the value of the useCoupon property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setUseCoupon(String value) {
                this.useCoupon = value;
            }

            /**
             * Gets the value of the logisticsFee property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getLogisticsFee() {
                return logisticsFee;
            }

            /**
             * Sets the value of the logisticsFee property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setLogisticsFee(String value) {
                this.logisticsFee = value;
            }

            /**
             * Gets the value of the couponDiscount property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCouponDiscount() {
                return couponDiscount;
            }

            /**
             * Sets the value of the couponDiscount property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCouponDiscount(String value) {
                this.couponDiscount = value;
            }

            /**
             * Gets the value of the refundStatus property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getRefundStatus() {
                return refundStatus;
            }

            /**
             * Sets the value of the refundStatus property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setRefundStatus(String value) {
                this.refundStatus = value;
            }

            /**
             * Gets the value of the logisticsStatus property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getLogisticsStatus() {
                return logisticsStatus;
            }

            /**
             * Sets the value of the logisticsStatus property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setLogisticsStatus(String value) {
                this.logisticsStatus = value;
            }

            /**
             * Gets the value of the additionalTradeStatus property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getAdditionalTradeStatus() {
                return additionalTradeStatus;
            }

            /**
             * Sets the value of the additionalTradeStatus property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setAdditionalTradeStatus(String value) {
                this.additionalTradeStatus = value;
            }

            /**
             * Gets the value of the gmtSendGoods property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getGmtSendGoods() {
                return gmtSendGoods;
            }

            /**
             * Sets the value of the gmtSendGoods property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setGmtSendGoods(String value) {
                this.gmtSendGoods = value;
            }

            /**
             * Gets the value of the gmtRefund property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getGmtRefund() {
                return gmtRefund;
            }

            /**
             * Sets the value of the gmtRefund property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setGmtRefund(String value) {
                this.gmtRefund = value;
            }

            /**
             * Gets the value of the timeOut property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getTimeOut() {
                return timeOut;
            }

            /**
             * Sets the value of the timeOut property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setTimeOut(String value) {
                this.timeOut = value;
            }

            /**
             * Gets the value of the gmtClose property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getGmtClose() {
                return gmtClose;
            }

            /**
             * Sets the value of the gmtClose property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setGmtClose(String value) {
                this.gmtClose = value;
            }

            /**
             * Gets the value of the gmtLogisticsModify property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getGmtLogisticsModify() {
                return gmtLogisticsModify;
            }

            /**
             * Sets the value of the gmtLogisticsModify property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setGmtLogisticsModify(String value) {
                this.gmtLogisticsModify = value;
            }

            /**
             * Gets the value of the timeOutType property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getTimeOutType() {
                return timeOutType;
            }

            /**
             * Sets the value of the timeOutType property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setTimeOutType(String value) {
                this.timeOutType = value;
            }

            /**
             * Gets the value of the refundFee property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getRefundFee() {
                return refundFee;
            }

            /**
             * Sets the value of the refundFee property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setRefundFee(String value) {
                this.refundFee = value;
            }

            /**
             * Gets the value of the refundFlowType property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getRefundFlowType() {
                return refundFlowType;
            }

            /**
             * Sets the value of the refundFlowType property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setRefundFlowType(String value) {
                this.refundFlowType = value;
            }

            /**
             * Gets the value of the refundId property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getRefundId() {
                return refundId;
            }

            /**
             * Sets the value of the refundId property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setRefundId(String value) {
                this.refundId = value;
            }

            /**
             * Gets the value of the refundCashFee property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getRefundCashFee() {
                return refundCashFee;
            }

            /**
             * Sets the value of the refundCashFee property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setRefundCashFee(String value) {
                this.refundCashFee = value;
            }

            /**
             * Gets the value of the refundCouponFee property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getRefundCouponFee() {
                return refundCouponFee;
            }

            /**
             * Sets the value of the refundCouponFee property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setRefundCouponFee(String value) {
                this.refundCouponFee = value;
            }

            /**
             * Gets the value of the refundAgentPayFee property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getRefundAgentPayFee() {
                return refundAgentPayFee;
            }

            /**
             * Sets the value of the refundAgentPayFee property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setRefundAgentPayFee(String value) {
                this.refundAgentPayFee = value;
            }

            /**
             * Gets the value of the fundBillList property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getFundBillList() {
                return fundBillList;
            }

            /**
             * Sets the value of the fundBillList property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setFundBillList(String value) {
                this.fundBillList = value;
            }

        }

    }

}
