//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.12.01 at 03:21:14 ÏÂÎç CST 
//


package net.shopin.alipay.entity;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the net.shopin.alipay.entity package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: net.shopin.alipay.entity
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Alipay }
     * 
     */
    public Alipay createAlipay() {
        return new Alipay();
    }

    /**
     * Create an instance of {@link Alipay.Request }
     * 
     */
    public Alipay.Request createAlipayRequest() {
        return new Alipay.Request();
    }

    /**
     * Create an instance of {@link Alipay.Response.Trade }
     * 
     */
    public Alipay.Response.Trade createAlipayResponseTrade() {
        return new Alipay.Response.Trade();
    }

    /**
     * Create an instance of {@link Alipay.Request.Param }
     * 
     */
    public Alipay.Request.Param createAlipayRequestParam() {
        return new Alipay.Request.Param();
    }

    /**
     * Create an instance of {@link Alipay.Response }
     * 
     */
    public Alipay.Response createAlipayResponse() {
        return new Alipay.Response();
    }

}
