/*
1.传入参数为一Map以适应后续的变化,因为解析过程也是动态的
2.Map中设定各种输入参数:
输出：
head[Map],头部输出
	cfx_CheckSum;
	cfx_PriceFileDate;
	cfx_ConfigIdentifer;
	cfx_DateTimeStamp;
	cfx_PropDocumentIdentifier;
	cfx_CFXML;
	totalListPrice;
	orderType
rows[List<OrderProductLine>],行集输出
输入：
applyType,申请类型
disc,折扣
listType[newbox,mes,isu,soft],列表类别
qty,数量                                                                                                     
time,时间标记,检查本规则对输入数据是否在有效
bmsn[String[]],
xmlPath,
outPath,
cfrPath
*/

#created on: Dec 2, 2008
package com.zsgj.itil.rules

#list any import classes here.
import com.zsgj.itil.service.rules.ServiceRuleHelper;
import org.dom4j.Node;
import org.jbpm.graph.node.TaskNode;

import java.io.File;
import java.lang.reflect.InvocationTargetException;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.Date;
import com.zsgj.itil.service.rules.ServiceRuleHelper;

import org.apache.commons.beanutils.BeanUtils;
import org.dom4j.Document;
import org.dom4j.DocumentException;
import org.dom4j.Node;
import org.dom4j.io.SAXReader;

#declare any global variables here



function void serviceCataAlterStartStatus(Map $map){
	
	String dataId = (String)$map.get("dataId");	
	String alterFlag = (String)$map.get("alterFlag");
	String nodeId = (String)$map.get("nodeId");	
	String processId = (String)$map.get("processId");
	String nodeName = (String)$map.get("nodeName");		
	ServiceRuleHelper serviceRuleHelper=new ServiceRuleHelper();
	serviceRuleHelper.serviceCataAlterStartFlag(dataId,nodeId,nodeName,processId,alterFlag);
	
}
function String serviceCataAlterAuditStatus(Map $map){
	
	String dataId = (String)$map.get("dataId");	
	String nodeId = (String)$map.get("nodeId");	
	String alterFlag = (String)$map.get("alterFlag");
	String processId = (String)$map.get("processId");
	String nodeName = (String)$map.get("nodeName");		
	String result = (String)$map.get("result");	
	String comment = (String)$map.get("comment");
	ServiceRuleHelper serviceRuleHelper=new ServiceRuleHelper();
	String trans = serviceRuleHelper.serviceCataAlterAuditFlag(dataId,nodeId,nodeName,processId,result,comment,alterFlag);
	return trans;	
}
function String serviceCataAlterConfirmStatus(Map $map){

	String dataId = (String)$map.get("dataId");
	String oldDataId =(String)$map.get("oldDataId");
	String alterFlag = (String)$map.get("alterFlag");	
	String nodeId = (String)$map.get("nodeId");	
	String processId = (String)$map.get("processId");
	String nodeName = (String)$map.get("nodeName");		
	String result = (String)$map.get("result");	
	String comment = (String)$map.get("comment");
	ServiceRuleHelper serviceRuleHelper=new ServiceRuleHelper();
	String trans = serviceRuleHelper.serviceCataAlterConfirmFlag(oldDataId,dataId,nodeId,nodeName,processId,result,comment,alterFlag);
	return trans;	
}
function String serviceCataAlterBackStatus(Map $map){

	String dataId = (String)$map.get("dataId");		 	
	String nodeName = (String)$map.get("nodeName");	
	String alterFlag = (String)$map.get("alterFlag");	
	String nodeId = (String)$map.get("nodeId");	
	String processId = (String)$map.get("processId");
	String result = (String)$map.get("result");	
	String comment = (String)$map.get("comment");
	ServiceRuleHelper serviceRuleHelper=new ServiceRuleHelper();
	String tran = serviceRuleHelper.serviceCataAlterBackFlag(dataId,nodeId,nodeName,processId,result,comment,alterFlag);
	return tran;	
}

rule "serviceCataAlterStartNode"
	salience 1000 
	when
		$map: Map(
			this['ruleName'] =='serviceCataAlterStartNode'		
		)
	then	 	
	serviceCataAlterStartStatus($map);
	$map.put("transitionName","NOLEAVE");	
end

rule "serviceCataAlterAuditNode"
	salience 900 
	when
		$map: Map(
			this['ruleName'] =='serviceCataAlterAuditNode'		
		)
	then	
	$map.put("transitionName",serviceCataAlterAuditStatus($map));	
end

rule "serviceCataAlterConfirmNode"
	salience 900 
	when
		$map: Map(
			this['ruleName'] =='serviceCataAlterConfirmNode'		
		)
	then	
	$map.put("transitionName",serviceCataAlterConfirmStatus($map));	
end

rule "serviceCataAlterBackNode"
	salience 800 
	when
		$map: Map(
			this['ruleName'] =='serviceCataAlterBackNode'		
		)
	then	
	$map.put("transitionName",serviceCataAlterBackStatus($map));		
end

