
package net.shopin.ldap.ws.client;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "SystemWSImplService", targetNamespace = "http://service.ws.ldap.shopin.net/", wsdlLocation = "http://localhost:8081/uac/services/sysService?wsdl")
public class SystemWSImplService
    extends Service
{

    private static URL SYSTEMWSIMPLSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(net.shopin.ldap.ws.client.SystemWSImplService.class.getName());
    private static SystemWSImplService systemWSImplService = null;

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = net.shopin.ldap.ws.client.SystemWSImplService.class.getResource(".");
            url = new URL(baseUrl, "http://localhost:8081/uac/services/sysService?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:8081/uac/services/sysService?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        SYSTEMWSIMPLSERVICE_WSDL_LOCATION = url;
    }

    public SystemWSImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SystemWSImplService() {
        super(SYSTEMWSIMPLSERVICE_WSDL_LOCATION, new QName("http://service.ws.ldap.shopin.net/", "SystemWSImplService"));
    }

    /**
     * 
     * @return
     *     returns SystemWSImpl
     */
    @WebEndpoint(name = "SystemWSImplPort")
    public SystemWSImpl getSystemWSImplPort() {
        return super.getPort(new QName("http://service.ws.ldap.shopin.net/", "SystemWSImplPort"), SystemWSImpl.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SystemWSImpl
     */
    @WebEndpoint(name = "SystemWSImplPort")
    public SystemWSImpl getSystemWSImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.ws.ldap.shopin.net/", "SystemWSImplPort"), SystemWSImpl.class, features);
    }
    
    public synchronized static SystemWSImpl getPort(String urlStr){

        //每次getPort都是最新的,这样就不会造成统一安全重启后，其他子系统没重启远程调用异常的问题
        if(systemWSImplService==null){
            URL url = null;
            try {
                URL baseUrl;
                baseUrl = SystemWSImplService.class.getResource(".");
                url = new URL(baseUrl, urlStr);
            } catch (MalformedURLException e) {
                logger.warning("Failed to create URL for the wsdl Location: '" + urlStr + "', retrying as a local file");
                logger.warning(e.getMessage());
            }
            SYSTEMWSIMPLSERVICE_WSDL_LOCATION = url;
            systemWSImplService = new SystemWSImplService(SYSTEMWSIMPLSERVICE_WSDL_LOCATION, new QName("http://service.ws.ldap.shopin.net/", "SystemWSImplService"));
        }
        return systemWSImplService.getSystemWSImplPort();
    }
    
    public static void main(String [] args){
    	
    	String urlStr = "http://localhost:8081/uac/services/sysService?wsdl";
    	SystemWSImpl port = SystemWSImplService.getPort(urlStr);
        port.getDeptList();
    }

}
