/*
1.传入参数为一Map以适应后续的变化,因为解析过程也是动态的
2.Map中设定各种输入参数:
输出：
head[Map],头部输出
	cfx_CheckSum;
	cfx_PriceFileDate;
	cfx_ConfigIdentifer;
	cfx_DateTimeStamp;
	cfx_PropDocumentIdentifier;
	cfx_CFXML;
	totalListPrice;
	orderType
rows[List<OrderProductLine>],行集输出
输入：
applyType,申请类型
disc,折扣
listType[newbox,mes,isu,soft],列表类别
qty,数量                                                                                                     
time,时间标记,检查本规则对输入数据是否在有效
bmsn[String[]],
xmlPath,
outPath,
cfrPath
*/

#created on: Dec 2, 2008
package com.digitalchina.info.framework.util.idgen

#list any import classes here.

import org.dom4j.Node;
import org.jbpm.graph.node.TaskNode;

import java.io.File;
import java.lang.reflect.InvocationTargetException;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.Date;
import com.zsgj.info.framework.util.idgen.IdGenRuleMethodHelper;
import com.zsgj.info.framework.util.idgen.IdGenRuleHelper;

import org.apache.commons.beanutils.BeanUtils;
import org.dom4j.Document;
import org.dom4j.DocumentException;
import org.dom4j.Node;
import org.dom4j.io.SAXReader;
import com.zsgj.info.framework.security.entity.Department;

#declare any global variables here

function String getTableCurrentGeneratedId(Map $map){

	String prefix = (String)$map.get("prefix");		 	
	String length = (String)$map.get("length");	
	String latestValue = (String)$map.get("latestValue");	
	Department dept = (Department)$map.get("dept");	
	
	IdGenRuleMethodHelper idGenRuleHelper = new IdGenRuleMethodHelper();
	
	String result = idGenRuleHelper.getTableCurrentGeneratedId(prefix,length,latestValue,dept);
	return result;	
}

rule "systemTableIdGen"
	salience 1000 
	when
		$map: Map(
			this['ruleName'] =='systemTableIdGen'		
		)
	then	 	
	
	$map.put("result", getTableCurrentGeneratedId($map));	
end


