/*
1.传入参数为一Map以适应后续的变化,因为解析过程也是动态的
2.Map中设定各种输入参数:
输出：
head[Map],头部输出
	cfx_CheckSum;
	cfx_PriceFileDate;
	cfx_ConfigIdentifer;
	cfx_DateTimeStamp;
	cfx_PropDocumentIdentifier;
	cfx_CFXML;
	totalListPrice;
	orderType
rows[List<OrderProductLine>],行集输出
输入：
applyType,申请类型
disc,折扣
listType[newbox,mes,isu,soft],列表类别
qty,数量                                                                                                     
time,时间标记,检查本规则对输入数据是否在有效
bmsn[String[]],
xmlPath,
outPath,
cfrPath
*/

#created on: Dec 2, 2008
package com.digitalchina.itil.rules

#list any import classes here.
/*
import com.digitalchina.ibmb2b.order.rules.RuleConst;
import com.digitalchina.ibmb2b.order.rules.OrderRuleHelper;
import com.digitalchina.ibmb2b.order.entity.OrderProductLine; 
*/
import com.digitalchina.itil.workflow.rules.EventProcessRuleHelper;
import org.dom4j.Node;
import org.jbpm.graph.node.TaskNode;

import java.io.File;
import java.lang.reflect.InvocationTargetException;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.Date;

import org.apache.commons.beanutils.BeanUtils;
import org.dom4j.Document;
import org.dom4j.DocumentException;
import org.dom4j.Node;
import org.dom4j.io.SAXReader;

#declare any global variables here



function void eventStartStatus(Map $map){
	
	String dataId = (String)$map.get("dataId");	
	String nodeId = (String)$map.get("nodeId");	
	String processId = (String)$map.get("processId");
	String nodeName = (String)$map.get("nodeName");		
	EventProcessRuleHelper processRuleHelper=new EventProcessRuleHelper();
	processRuleHelper.eventStartFlag(dataId,nodeId,nodeName,processId);
	
}
function String engineerProcessStatus(Map $map){

	String dataId = (String)$map.get("dataId");	
	String nodeId = (String)$map.get("nodeId");	
	String processId = (String)$map.get("processId");
	String nodeName = (String)$map.get("nodeName");		
	String result = (String)$map.get("next");	
	String comment = (String)$map.get("comment");
	EventProcessRuleHelper processRuleHelper=new EventProcessRuleHelper();
	String trans = processRuleHelper.engineerProcessFlag(dataId,nodeId,nodeName,processId,result,comment);
	return trans;	
}
function String headerProcessStatus(Map $map){

	String dataId = (String)$map.get("dataId");		 	
	String nodeName = (String)$map.get("nodeName");	
	String nodeId = (String)$map.get("nodeId");	
	String processId = (String)$map.get("processId");
	String result = (String)$map.get("next");	
	String comment = (String)$map.get("comment");
	EventProcessRuleHelper processRuleHelper=new EventProcessRuleHelper();
	String tran = processRuleHelper.headerProcessFlag(dataId,nodeId,nodeName,processId,result,comment);
	return tran;	
}
function String otherOrgProcessStatus(Map $map){

	String dataId = (String)$map.get("dataId");		 	
	String nodeName = (String)$map.get("nodeName");	
	String nodeId = (String)$map.get("nodeId");	
	String processId = (String)$map.get("processId");
	String result = (String)$map.get("next");	
	String comment = (String)$map.get("comment");
	EventProcessRuleHelper processRuleHelper=new EventProcessRuleHelper();
	String tran = processRuleHelper.otherOrgProcessFlag(dataId,nodeId,nodeName,processId,result,comment);
	return tran;	
}
function String userConfirmStatus(Map $map){

	String dataId = (String)$map.get("dataId");		 	
	String nodeName = (String)$map.get("nodeName");	
	String nodeId = (String)$map.get("nodeId");	
	String processId = (String)$map.get("processId");
	String result = (String)$map.get("next");	
	String comment = (String)$map.get("comment");
	EventProcessRuleHelper processRuleHelper=new EventProcessRuleHelper();
	String tran = processRuleHelper.userConfirmFlag(dataId,nodeId,nodeName,processId,result,comment);
	return tran;	
}
function void endStatus(Map $map){

	String dataId = (String)$map.get("dataId");		 	
	String nodeName = (String)$map.get("nodeName");	
	String nodeId = (String)$map.get("nodeId");	
	String processId = (String)$map.get("processId");
	String result = (String)$map.get("next");	
	String comment = (String)$map.get("comment");
	EventProcessRuleHelper processRuleHelper=new EventProcessRuleHelper();
	processRuleHelper.endFlag(dataId,nodeId,nodeName,processId,result,comment);
}

rule "eventStartNode"
	salience 1000 
	when
		$map: Map(
			this['ruleName'] =='eventStartNode'		
		)
	then	 	
	eventStartStatus($map);
	$map.put("transitionName","NOLEAVE");	
end

rule "engineerProcessNode"
	salience 900 
	when
		$map: Map(
			this['ruleName'] =='engineerProcessNode'		
		)
	then	
	$map.put("transitionName",engineerProcessStatus($map));	
end

rule "headerProcessNode"
	salience 800 
	when
		$map: Map(
			this['ruleName'] =='headerProcessNode'		
		)
	then	
	$map.put("transitionName",headerProcessStatus($map));		
end

rule "otherOrgProcessNode"
	salience 800 
	when
		$map: Map(
			this['ruleName'] =='otherOrgProcessNode'		
		)
	then	
	$map.put("transitionName",otherOrgProcessStatus($map));		
end

rule "userConfirmNode"
	salience 800 
	when
		$map: Map(
			this['ruleName'] =='userConfirmNode'		
		)
	then	
	$map.put("transitionName",userConfirmStatus($map));		
end

rule "endNode"
	salience 800 
	when
		$map: Map(
			this['ruleName'] =='endNode'		
		)
	then	
	endStatus($map);
	$map.put("transitionName","");		
end