//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.06.04 at 11:37:13 AM CST 
//


package cn.shopin.syndata.entity;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Dept complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Dept">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="deptcode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="deptname" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="parentdept" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="startdate" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="enddate" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="isdelete" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="customizeSQL" type="{http://syndata.shopin.cn}customizeSQL" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="isSyn" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="tablename" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Dept", propOrder = {
    "deptcode",
    "deptname",
    "parentdept",
    "startdate",
    "enddate",
    "isdelete",
    "customizeSQL"
})
public class Dept {

    @XmlElement(required = true)
    protected String deptcode;
    @XmlElement(required = true)
    protected String deptname;
    @XmlElement(required = true)
    protected String parentdept;
    @XmlElement(required = true)
    protected String startdate;
    @XmlElement(required = true)
    protected String enddate;
    @XmlElement(required = true)
    protected String isdelete;
    protected CustomizeSQL customizeSQL;
    @XmlAttribute(name = "isSyn")
    protected Boolean isSyn;
    @XmlAttribute(name = "tablename")
    protected String tablename;

    /**
     * Gets the value of the deptcode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDeptcode() {
        return deptcode;
    }

    /**
     * Sets the value of the deptcode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDeptcode(String value) {
        this.deptcode = value;
    }

    /**
     * Gets the value of the deptname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDeptname() {
        return deptname;
    }

    /**
     * Sets the value of the deptname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDeptname(String value) {
        this.deptname = value;
    }

    /**
     * Gets the value of the parentdept property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getParentdept() {
        return parentdept;
    }

    /**
     * Sets the value of the parentdept property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setParentdept(String value) {
        this.parentdept = value;
    }

    /**
     * Gets the value of the startdate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStartdate() {
        return startdate;
    }

    /**
     * Sets the value of the startdate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStartdate(String value) {
        this.startdate = value;
    }

    /**
     * Gets the value of the enddate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEnddate() {
        return enddate;
    }

    /**
     * Sets the value of the enddate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEnddate(String value) {
        this.enddate = value;
    }

    /**
     * Gets the value of the isdelete property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIsdelete() {
        return isdelete;
    }

    /**
     * Sets the value of the isdelete property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIsdelete(String value) {
        this.isdelete = value;
    }

    /**
     * Gets the value of the customizeSQL property.
     * 
     * @return
     *     possible object is
     *     {@link CustomizeSQL }
     *     
     */
    public CustomizeSQL getCustomizeSQL() {
        return customizeSQL;
    }

    /**
     * Sets the value of the customizeSQL property.
     * 
     * @param value
     *     allowed object is
     *     {@link CustomizeSQL }
     *     
     */
    public void setCustomizeSQL(CustomizeSQL value) {
        this.customizeSQL = value;
    }

    /**
     * Gets the value of the isSyn property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isIsSyn() {
        if (isSyn == null) {
            return false;
        } else {
            return isSyn;
        }
    }

    /**
     * Sets the value of the isSyn property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsSyn(Boolean value) {
        this.isSyn = value;
    }

    /**
     * Gets the value of the tablename property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTablename() {
        return tablename;
    }

    /**
     * Sets the value of the tablename property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTablename(String value) {
        this.tablename = value;
    }

}
