//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.05.25 at 01:58:32 PM CST 
//


package cn.shopin.syndata.entity;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SynData complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SynData">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="dataBase" type="{http://syndata.shopin.cn}DataBase"/>
 *         &lt;element name="tableinfo" type="{http://syndata.shopin.cn}TableInfo"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SynData", propOrder = {
    "dataBase",
    "tableinfo"
})
@XmlRootElement(name = "SynData")
public class SynData {

    @XmlElement(required = true)
    protected DataBase dataBase;
    @XmlElement(required = true)
    protected TableInfo tableinfo;

    /**
     * Gets the value of the dataBase property.
     * 
     * @return
     *     possible object is
     *     {@link DataBase }
     *     
     */
    public DataBase getDataBase() {
        return dataBase;
    }

    /**
     * Sets the value of the dataBase property.
     * 
     * @param value
     *     allowed object is
     *     {@link DataBase }
     *     
     */
    public void setDataBase(DataBase value) {
        this.dataBase = value;
    }

    /**
     * Gets the value of the tableinfo property.
     * 
     * @return
     *     possible object is
     *     {@link TableInfo }
     *     
     */
    public TableInfo getTableinfo() {
        return tableinfo;
    }

    /**
     * Sets the value of the tableinfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link TableInfo }
     *     
     */
    public void setTableinfo(TableInfo value) {
        this.tableinfo = value;
    }

}
